name: Konnect Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - konnect-api-resource.yaml
      - openapi.yaml

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kongctl
        uses: kong/setup-kongctl@v1

      - name: Apply Flights API
        env:
          KONGCTL_DEFAULT_KONNECT_PAT: ${{ secrets.KONNECT_TOKEN }}
          KONGCTL_DEFAULT_KONNECT_REGION: us
        run: kongctl apply -f konnect-api-resource.yaml --auto-approve
